autoindent = true
autoclose = true
cursor = "block"
theme = "monokai"
syntax = true
tabsize = 4
tabstospaces = true
scrollmargin = 5
hscrollmargin = 5
linenums = true
softwrap = false
wordwrap = false
clipboard = "external"
cursorline = true
incsearch = true
saveundo = true
savecursor = true
savehistory = true

[makefile]
tabstospaces = false
