autoindent = true
autoclose = true
autoformat = false
cursor = "block"
theme = "molokai"
syntax = true
lsp = true
tabsize = 4
tabstospaces = true
detectindent = true
tabchar = "|"
textwidth = 79
scrollmargin = 3
hscrollmargin = 1
linenums = true
softwrap = true
wordwrap = false
clipboard = "external"
cursorline = true
incsearch = true
smartcase = true
saveundo = true
savecursor = true
savehistory = true

[makefile]
tabstospaces = false

[go]
tabstospaces = false
