color-column:
  fg: '#e4e4e4'
  bg: '#ffffff'
comment:
  fg: '#949494'
  bg: '#ffffff'
constant:
  fg: '#af5f00'
  bg: '#ffffff'
constant.number:
  fg: '#af5f5f'
  bg: '#ffffff'
constant.string:
  fg: '#af8700'
  bg: '#ffffff'
cursor-line:
  fg: '#e4e4e4'
  bg: '#ffffff'
default:
  fg: '#626262'
  bg: '#ffffff'
diff-added:
  fg: '#00af00'
  bg: '#ffffff'
diff-deleted:
  fg: '#d70000'
  bg: '#ffffff'
diff-modified:
  fg: '#ffaf00'
  bg: '#ffffff'
error:
  fg: '#ffffff'
  bg: '#d70000'
function:
  fg: '#d75f5f'
  bg: '#ffffff'
gutter-error:
  fg: '#ff005f'
  bg: '#ffffff'
gutter-warning:
  fg: '#af5fd7'
  bg: '#ffffff'
hlsearch:
  fg: '#ffffff'
  bg: '#af8700'
keyword:
  fg: '#0087d7'
  bg: '#ffffff'
line-number:
  fg: '#949494'
  bg: '#e4e4e4'
preproc:
  fg: '#008700'
  bg: '#ffffff'
special:
  fg: '#d75f5f'
  bg: '#ffffff'
statusline:
  fg: '#626262'
  bg: '#e4e4e4'
tabbar:
  fg: '#626262'
  bg: '#e4e4e4'
todo:
  fg: '#949494'
  bg: '#ffffff'
type:
  fg: '#5f5faf'
  bg: '#ffffff'
type.extended:
  fg: '#626262'
  bg: '#ffffff'
underlined:
  fg: '#626262'
  bg: '#ffffff'
  attr:
  - underline
