color-column:
  fg: '#2c2c2c'
  bg: '#242424'
comment:
  fg: '#707070'
  bg: '#242424'
constant:
  fg: '#7a9ec2'
  bg: '#242424'
constant.string:
  fg: '#6a8759'
  bg: '#242424'
constant.string.char:
  fg: '#6a8759'
  bg: '#242424'
current-line-number:
  fg: '#666666'
  bg: '#242424'
cursorline:
  bg: '#2c2c2c'
default:
  fg: '#cccccc'
  bg: '#242424'
diff-added:
  fg: '#00af00'
  bg: '#242424'
diff-deleted:
  fg: '#d70000'
  bg: '#242424'
diff-modified:
  fg: '#ffaf00'
  bg: '#242424'
error:
  fg: '#cb4b16'
  bg: '#242424'
  attr:
  - bold
function:
  fg: '#cc8242'
  bg: '#242424'
gutter-error:
  fg: '#cb4b16'
  bg: '#242424'
gutter-warning:
  fg: '#e6db74'
  bg: '#242424'
hidden-char:
  fg: '#4f4f4f'
  bg: '#242424'
hlsearch:
  fg: '#cccccc'
  bg: '#32593d'
keyword:
  fg: '#cc8242'
  bg: '#242424'
line-number:
  fg: '#666666'
  bg: '#2c2c2c'
preproc:
  fg: '#cc8242'
  bg: '#242424'
special:
  fg: '#cc8242'
  bg: '#242424'
statusline:
  fg: '#242424'
  bg: '#cccccc'
tabbar:
  fg: '#242424'
  bg: '#cccccc'
todo:
  fg: '#d33682'
  bg: '#242424'
  attr:
  - bold
type:
  fg: '#cc8242'
  bg: '#242424'
type.extended:
  fg: '#-00001'
  bg: '#242424'
underlined:
  fg: '#d33682'
  bg: '#242424'
