color-column:
  fg: '#44475a'
  bg: '#282a36'
comment:
  fg: '#6272a4'
  bg: '#282a36'
constant:
  fg: '#bd93f9'
  bg: '#282a36'
constant.number:
  fg: '#f8f8f2'
  bg: '#282a36'
constant.string:
  fg: '#f1fa8c'
  bg: '#282a36'
current-line-number:
  fg: '#f8f8f2'
  bg: '#282a36'
cursor-line:
  fg: '#44475a'
  bg: '#f8f8f2'
default:
  fg: '#f8f8f2'
  bg: '#282a36'
diff-added:
  fg: '#50fa7b'
  bg: '#282a36'
diff-deleted:
  fg: '#ff5555'
  bg: '#282a36'
diff-modified:
  fg: '#ffb86c'
  bg: '#282a36'
error:
  fg: '#ff5555'
  bg: '#282a36'
  attr:
  - bold
function:
  fg: '#ff79c6'
  bg: '#282a36'
gutter-error:
  fg: '#ff5555'
  bg: '#282a36'
gutter-warning:
  fg: '#e6db74'
  bg: '#282a36'
hidden-char:
  fg: '#6272a4'
  bg: '#282a36'
hlsearch:
  fg: '#282a36'
  bg: '#50fa7b'
identifier.class:
  fg: '#8be9fd'
  bg: '#282a36'
identifier.var:
  fg: '#f8f8f2'
  bg: '#282a36'
keyword:
  fg: '#ff79c6'
  bg: '#282a36'
line-number:
  fg: '#6272a4'
  bg: '#282a36'
preproc:
  fg: '#ff79c6'
  bg: '#282a36'
special:
  fg: '#ff79c6'
  bg: '#282a36'
statusline:
  fg: '#282a36'
  bg: '#f8f8f2'
tabbar:
  fg: '#282a36'
  bg: '#f8f8f2'
todo:
  fg: '#ff79c6'
  bg: '#282a36'
  attr:
  - bold
type:
  fg: '#8be9fd'
  bg: '#282a36'
  attr:
  - italic
type.extended:
  fg: '#-00001'
  bg: '#282a36'
type.keyword:
  fg: '#ff79c6'
  bg: '#282a36'
underlined:
  fg: '#ff79c6'
  bg: '#282a36'
