default:
    fg: 252
    bg: 233
comment:
    fg: 59
    bg: 233
line-number:
    fg: 250
    bg: 236
constant:
    fg: 135
    bg: 233
constant.string:
    fg: 144
    bg: 233
constant.string.char:
    fg: "#BDE6AD"
    bg: 233
constant.string.escape:
    fg: "#AE81FF"
    bg: 233
symbol.tag:
    fg: "#AE81FF"
    bg: 233
preproc:
    fg: "#CB4B16"
    bg: 233
function:
    fg: "#A6E22E"
    bg: 233
keyword:
    fg: "#F92672"
    bg: 233
type:
    fg: "#66D9EF"
    bg: 233
special:
    fg: "#A6E22E"
    bg: 233
underlined:
    fg: "#D33672"
    bg: 233
    attr: ["underline"]
error:
    fg: "#CB4B16"
    bg: 233
    attr: ["bold"]
todo:
    fg: "#D33682"
    bg: 233
    attr: ["bold"]
statusline:
    fg: 238
    bg: 253
hidden-char:
    fg: "#505050"
    bg: 233
