color-column:
  fg: '#323232'
  bg: '#282828'
comment:
  fg: '#75715e'
  bg: '#282828'
constant:
  fg: '#ae81ff'
  bg: '#282828'
constant.string:
  fg: '#e6db74'
  bg: '#282828'
constant.string.char:
  fg: '#bde6ad'
  bg: '#282828'
current-line-number:
  fg: '#aaaaaa'
  bg: '#282828'
cursorline:
  fg: '#323232'
  bg: '#323232'
default:
  fg: '#f8f8f2'
  bg: '#282828'
diff-added:
  fg: '#00af00'
  bg: '#282828'
diff-deleted:
  fg: '#d70000'
  bg: '#282828'
diff-modified:
  fg: '#ffaf00'
  bg: '#282828'
error:
  fg: '#cb4b16'
  bg: '#282828'
  attr:
  - bold
function:
  fg: '#a6e22e'
  bg: '#282828'
function.builtin:
  fg: '#fd971f'
  bg: '#282828'
gutter-error:
  fg: '#cb4b16'
  bg: '#282828'
gutter-warning:
  fg: '#e6db74'
  bg: '#282828'
hidden-char:
  fg: '#505050'
  bg: '#282828'
keyword:
  fg: '#f92672'
  bg: '#282828'
line-number:
  fg: '#aaaaaa'
  bg: '#323232'
preproc:
  fg: '#cb4b16'
  bg: '#282828'
special:
  fg: '#a6e22e'
  bg: '#282828'
statusline:
  fg: '#282828'
  bg: '#f8f8f2'
tabbar:
  fg: '#282828'
  bg: '#f8f8f2'
todo:
  fg: '#d33682'
  bg: '#282828'
  attr:
  - bold
type:
  fg: '#66d9ef'
  bg: '#282828'
type.extended:
  fg: '#-00001'
  bg: '#282828'
underlined:
  fg: '#d33682'
  bg: '#282828'
