color-column:
  fg: '#444444'
  bg: '#3a3a3a'
comment:
  fg: '#87af87'
  bg: '#3a3a3a'
constant:
  fg: '#d7afaf'
  bg: '#3a3a3a'
constant.number:
  fg: '#87d7d7'
  bg: '#3a3a3a'
constant.string:
  fg: '#d78787'
  bg: '#3a3a3a'
current-line-number:
  fg: '#d7d7d7'
  bg: '#3a3a3a'
cursor-line:
  fg: '#444444'
  bg: '#3a3a3a'
default:
  fg: '#d7d7d7'
  bg: '#3a3a3a'
diff-added:
  fg: '#00af00'
  bg: '#3a3a3a'
diff-deleted:
  fg: '#d70000'
  bg: '#3a3a3a'
diff-modified:
  fg: '#ffaf00'
  bg: '#3a3a3a'
error:
  fg: '#87d7af'
  bg: '#303030'
function:
  fg: '#d7afaf'
  bg: '#3a3a3a'
gutter-error:
  fg: '#3a3a3a'
  bg: '#d78787'
gutter-warning:
  fg: '#d78787'
  bg: '#3a3a3a'
hidden-char:
  fg: '#444444'
  bg: '#3a3a3a'
hlsearch:
  fg: '#ffffd7'
  bg: '#005f00'
keyword:
  fg: '#ffd7af'
  bg: '#3a3a3a'
line-number:
  fg: '#a8a8a8'
  bg: '#444444'
preproc:
  fg: '#ffd7af'
  bg: '#3a3a3a'
special:
  fg: '#d7afaf'
  bg: '#3a3a3a'
statusline:
  fg: '#d7d787'
  bg: '#303030'
tabbar:
  fg: '#d7d787'
  bg: '#303030'
todo:
  fg: '#e4e4e4'
  bg: '#3a3a3a'
  attr:
  - bold
type:
  fg: '#d7d7af'
  bg: '#3a3a3a'
underlined:
  fg: '#d7d7d7'
  bg: '#3a3a3a'
