autoindent = true
cursor = "block"
theme = "monokai"
syntax = true
tabsize = 4
tabstospaces = true
charmap = "|  "
scrollmargin = 3
hscrollmargin = 1
linenums = true
softwrap = false
wordwrap = false
mode = "micro"
clipboard = "external"
cursorline = true

[makefile]

tabstospaces = false
